#!/bin/sh

USER=$(ls /home)

sxhkd /home/$USER/.config/sxhkd/*.hk &
picom --experimental-backends -b
unclutter -b
feh --bg-scale --no-fehbg /home/$USER/.config/wallpaper.jpg
pcmanfm -d
lxpolkit &
playerctld daemon
xset s off -dpms
export QT_STYLE_OVERRIDE=kvantum
exec spectrwm
