#!/bin/bash
#Shortcuts

USER="$(ls /home)"

fgrep "bind" /home/$USER/.spectrwm.conf | sed -n 's/.*= //p' | sed 's/MOD/Super/g' | sed 's/Mod1/Alt/g' > /tmp/kb.txt
fgrep "#" /home/$USER/.config/sxhkd/sxhkdrc | sed 's/super/Super/g' | sed 's/alt/Alt/g' >> /tmp/kb.txt

output=$(cat /tmp/kb.txt | rofi -theme center -dmenu -p Shortcuts -i)
if [[ $output == "" ]]; then exit 1;
else xdotool key $output; fi
