#!/bin/sh
#Wifi

nmcli -t d wifi rescan
OUTPUT="$(nmcli -t -g SSID,BARS device wifi list | grep -v ^\$ | uniq -u | rofi -theme right -dmenu -p Wifi -i)"
[ -z "$OUTPUT" ] && exit 1
PASS="$(zenity --title "Rofi-WiFi" --entry --text "Enter password for $OUTPUT")"
[ -z "$PASS" ] && exit 1
if nmcli device wifi connect "$OUTPUT" password "$PASS"
then
	dunstify -I /usr/share/icons/Arc/devices/symbolic/network-wireless-symbolic.svg -h string:x-dunst-stack-tag:network "Connected"
else
	dunstify -I /usr/share/icons/Arc/devices/symbolic/network-wireless-symbolic.svg -h string:x-dunst-stack-tag:network "Connection failed"
fi
exit 0
